spring:
  datasource:
    url: jdbc:postgresql://localhost:5435/mtg_decklist
    username: mtg_decklist
    password: azerty123456
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

mtg-decklist:
  scryfall:
    api:
      url: https://api.scryfall.com/
      card:
        relatedCards:
          relationTypesToExclude: combo_piece

